version: "3.3"

services:
  database_ignite: 
    image: postgres
    container_name: database_ignite
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - database-ignite
    
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - rentx-network
      - database-ignite
    # links: 
    #   - database_ignite
    # depends_on:
    #   - database_ignite
volumes:
  pgdata:
    driver: local


networks:
  rentx-network: {}
  database-ignite: {}